name: Website Deploy
on:
  push:
    branches:
      - master
jobs:
  app-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
#    needs: laravel-tests
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          server-dir: bpo/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/tests/**
            **/README.md
            **/phpunit.xml
            aliases
            Vagrantfile
            after.sh
            /.vagrant
            **/.idea/**
            Homestead.yml
